"""
RIKAA V1.2 — Planning Engine Blueprint
Chapter 6.4: Hermes Communication Contract — Hermes → Runtime Response
========================================================================

Defines the standardized response returned by Hermes after completing a
HermesRequest.

This chapter specifies only the communication contract. It does not
describe Hermes internal implementation, execution logic, or how the
response is constructed internally.

==============================================================================
6.4.1 Purpose
==============================================================================

HermesResponse is the standardized output returned by Hermes after
completing the planning and analytical work requested by Runtime.
Runtime depends only on the HermesResponse and never on Hermes internal
implementation, execution state, or intermediate outputs.

The response contract ensures that:

- Runtime receives a predictable, well-defined response for every
  request, regardless of the internal complexity of the execution.

- Hermes can change its internal implementation without affecting
  Runtime, as long as the response contract is honoured.

- The response is versioned, enabling controlled evolution of the
  response schema without breaking existing consumers.

==============================================================================
6.4.2 Design Principles
==============================================================================

The HermesResponse contract adheres to the following design principles:

1. Standardized Structure

   Every Hermes-to-Runtime interaction uses the same response structure.
   There is no ad-hoc or custom response format.

2. Self-contained

   Every HermesResponse contains all information required by Runtime to
   process the result. Runtime does not need to query Hermes for
   additional context or clarification.

3. Version Stable

   The response schema is versioned. Changes to the schema are governed
   by the versioning policy defined in the Communication Contract.

4. Machine Readable

   The response is structured for programmatic consumption. All fields
   have defined types and semantics. Runtime processes the response with
   deterministic logic.

5. Immutable After Return

   Once Hermes returns a HermesResponse, the response is immutable.
   Neither Hermes nor Runtime modifies the response after it has been
   delivered.

==============================================================================
6.4.3 HermesResponse Schema
==============================================================================

The HermesResponse contains the following fields:

| Field          | Type     | Required | Description |
|----------------|----------|----------|-------------|
| version        | string   | Required | Schema version of the response contract |
| status         | string   | Required | Execution status: SUCCESS, PARTIAL_SUCCESS, or FAILED |
| decision       | object   | Required | Primary business output produced by Hermes |
| confidence     | object   | Required | Confidence score and level for the decision |
| execution_plan | array    | Required | Executable tasks or actions generated by Hermes |
| warnings       | array    | Required | Recoverable issues encountered during execution |
| metrics        | object   | Required | Execution statistics for monitoring |
| trace          | object   | Required | Execution tracing information for diagnostics |
| reasoning      | string   | Optional | Structured explanation for logging and auditing |

Note: Warnings, Metrics, and Trace shall always be present. When no data
exists, they shall use empty structures (for example, `[]` or `{}`)
instead of being omitted. This simplifies Runtime parsing and avoids
unnecessary null checks.

==============================================================================
6.4.4 Field Definitions
==============================================================================

version
-------

Purpose: Identifies the schema version of the response contract.

Required: Yes.

Runtime Usage: Runtime reads the version to determine which schema rules
apply to the response. Runtime verifies that the version is compatible
with the request version.

status
------

Purpose: Indicates the overall execution status of the request.

Required: Yes.

Runtime Usage: Runtime checks the status to determine whether the
execution completed successfully, partially succeeded, or failed. The
status determines the subsequent pipeline flow.

decision
--------

Purpose: The primary business output produced by Hermes. Contains the
result of the planning and analytical work.

Required: Yes.

Runtime Usage: Runtime stores the decision in the Runtime Context. The
decision becomes part of the Runtime execution state and is available
for downstream processing.

confidence
----------

Purpose: Indicates the confidence level of the decision produced by
Hermes.

Required: Yes.

Runtime Usage: Runtime stores the confidence in the Runtime Context.
Runtime may expose confidence to callers but shall not rely solely on
confidence for execution control.

reasoning
---------

Purpose: A structured explanation of the decision produced by Hermes.
Intended for logging, auditing, and user-facing explanations.

Required: No.

Runtime Usage: Runtime stores reasoning for diagnostic and audit
purposes. Runtime must never branch execution based on reasoning text.

execution_plan
--------------

Purpose: A list of executable tasks or actions generated by Hermes as
part of its planning and analytical work.

Required: Yes.

Runtime Usage: Runtime stores the execution plan in the Runtime
Context. The plan is passed to downstream execution components.

warnings
--------

Purpose: A list of recoverable issues encountered during execution.
Warnings indicate conditions that did not cause failure but may be
relevant for downstream processing or user awareness.

Required: Yes. Shall use an empty array when no warnings exist.

Runtime Usage: Runtime stores warnings in the Runtime Context. Warnings
may be included in the final Runtime Response. Warnings never represent
execution failure.

metrics
-------

Purpose: Execution statistics produced by Hermes describing Hermes
execution only. Provides observability into Hermes execution without
exposing internal implementation details. Metrics shall not include
Runtime processing statistics.

Required: Yes. Shall use an empty object when no metrics are collected.

Runtime Usage: Runtime stores metrics for monitoring and optimization
purposes. Metrics never affect Runtime execution flow.

trace
-----

Purpose: Execution tracing information for diagnostics and cross-
component correlation. Trace is implementation dependent. A minimal
implementation may contain only identifiers (request_id, execution_id).
Detailed pipeline traces are optional.

Required: Yes. Shall use an empty object when no trace data is available.

Runtime Usage: Runtime stores trace information for diagnostic purposes.
Trace information never affects Runtime behaviour.

==============================================================================
6.4.5 Hermes Status
==============================================================================

The HermesResponse status field shall contain one of the following
values:

SUCCESS
-------

Execution completed successfully. All required outputs were produced.
No errors occurred. The decision, confidence, and execution_plan fields
contain valid data.

Runtime Behaviour: Runtime continues the pipeline normally. The
Response Builder constructs the final Runtime Response using the
HermesResponse data.

PARTIAL_SUCCESS
---------------

Execution completed with recoverable issues. The primary outputs
(decision, execution_plan) were produced but with reduced quality,
coverage, or confidence. Warnings describe the specific issues.

Runtime Behaviour: Runtime continues the pipeline normally. Warnings are
recorded in the Runtime Context and may be included in the final Runtime
Response. The decision and execution_plan shall still be considered
valid for downstream processing.

FAILED
------

Execution failed. Hermes could not produce a valid decision or
execution plan. The decision and execution_plan fields may be empty or
incomplete.

Runtime Behaviour: Runtime halts the pipeline. The error is propagated
through Runtime Error Handling (Runtime 0.6). The Response Builder
constructs a Runtime Error Response.

==============================================================================
6.4.6 Decision
==============================================================================

The decision field is the primary business output produced by Hermes. It
contains the result of the planning and analytical work requested by
Runtime.

Purpose: Provides the core result that Runtime stores in the Runtime
Context for downstream processing.

Structure: The decision is a structured object whose internal fields are
defined by Hermes. Runtime does not interpret the internal structure of
the decision beyond storing it in the Runtime Context.

Availability by Status:
- SUCCESS: decision is required and shall contain valid data.
- PARTIAL_SUCCESS: decision may be present. If present, it contains
  partial but valid data.
- FAILED: decision shall be None. No decision data is available.

Runtime Usage:
- Runtime stores the decision in the execution_context section of the
  Runtime Context.
- The decision becomes part of the execution state and is available for
  the Response Builder when constructing the final Runtime Response.
- Runtime does not modify, interpret, or validate the decision content.

Example structure (illustrative only):

  decision:
    - selected_strategy: "string"
    - alternatives: ["string", "string"]
    - rationale: "string"

The example above is illustrative. The actual structure is defined by
Hermes and may evolve independently.

==============================================================================
6.4.7 Confidence
==============================================================================

The confidence field indicates how confident Hermes is in the decision
it produced. Confidence is represented as a structured object with two
components:

Availability by Status:
- SUCCESS: confidence is required and shall contain a valid score and
  level.
- PARTIAL_SUCCESS: confidence may be present. If present, it reflects
  reduced confidence due to partial execution.
- FAILED: confidence shall be None. Runtime must not infer confidence
  from failed executions.

score
-----

A numeric representation of confidence. The score is a value between
0.0 and 1.0, where 0.0 indicates no confidence and 1.0 indicates
complete confidence.

level
-----

A categorical representation of confidence. The level provides a
human-readable classification of the confidence score.

Recommended confidence levels:

| Level | Score Range | Description |
|-------|-------------|-------------|
| VERY_HIGH | 0.90 – 1.00 | Maximum confidence. Decision is highly reliable. |
| HIGH | 0.70 – 0.89 | Strong confidence. Decision is reliable. |
| MEDIUM | 0.40 – 0.69 | Moderate confidence. Decision should be reviewed. |
| LOW | 0.20 – 0.39 | Low confidence. Decision may be unreliable. |
| VERY_LOW | 0.00 – 0.19 | Minimal confidence. Decision is likely unreliable. |

Runtime Usage:
- Runtime stores confidence in the Runtime Context.
- Runtime may expose confidence to callers for informational purposes.
- Runtime shall not rely solely on confidence for execution control
  decisions. Pipeline execution decisions are governed by the status
  field, not the confidence level.

==============================================================================
6.4.8 Reasoning
==============================================================================

The reasoning field contains a structured explanation of the decision
produced by Hermes. Reasoning is intended for:

- Logging: Recording why a particular decision was made.
- Auditing: Providing an auditable trail of decision rationale.
- User-facing explanations: Generating human-readable explanations of
  the system's output.

Structure: The reasoning field is an optional string whose content is
defined by Hermes. Runtime does not interpret the reasoning content.

Critical Rule:
Runtime must never branch execution based on reasoning text. Reasoning
is for explanation purposes only. Execution decisions shall be based
exclusively on structured fields (status, decision, confidence).

==============================================================================
6.4.9 Execution Plan
==============================================================================

The execution_plan field contains executable tasks or actions generated
by Hermes as part of its planning and analytical work.

Purpose: Provides the execution steps that downstream components use to
carry out the work determined by Hermes.

Structure: The execution_plan is an array of structured objects. Each
object represents a single task or action. The internal structure of
each task is defined by Hermes.

Runtime Usage:
- Runtime stores the execution_plan in the Runtime Context.
- The execution_plan is passed to downstream execution components for
  processing.
- Runtime shall preserve the execution order defined by Hermes.
- Runtime may copy the execution plan into RuntimeContext but shall not
  modify its content or execution order.
- Runtime shall not interpret the execution_plan contents beyond routing
  them to downstream components.

==============================================================================
6.4.10 Warnings
==============================================================================

The warnings field contains recoverable issues encountered by Hermes
during execution. Warnings inform Runtime and downstream components of
conditions that did not cause failure but may be relevant.

Warnings never represent execution failure. A response with warnings
shall have a status of SUCCESS or PARTIAL_SUCCESS, not FAILED.

Examples of warnings:

- LOW_CONFIDENCE: The decision confidence was lower than expected.
- FALLBACK_MODEL_USED: Hermes used a fallback model instead of the
  primary model.
- OPTIONAL_MODULE_SKIPPED: An optional module was skipped during
  execution.
- TIME_LIMIT_REACHED: Hermes reached a time limit and returned results
  before completing all planned work.

Runtime Usage:
- Runtime stores warnings in the Runtime Context warnings section.
- Warnings may be included in the final Runtime Response.
- Warnings do not alter the pipeline execution flow. The pipeline
  continues normally when warnings are present.
- Warnings are distinct from errors. Errors indicate execution failure;
  warnings indicate recoverable conditions.

==============================================================================
6.4.11 Metrics
==============================================================================

The metrics field contains execution statistics produced by Hermes.
Metrics provide observability into the execution without exposing
internal implementation details.

Examples of metrics:

- latency_ms: The total execution time in milliseconds.
- tokens_used: The number of tokens consumed during execution.
- modules_executed: The number of modules executed.

Runtime Usage:
- Runtime stores metrics for monitoring and optimization purposes.
- Metrics are recorded in the Runtime Context metadata section.
- Metrics never affect Runtime execution flow.
- Metrics may be included in operational dashboards and alerting
  systems.

==============================================================================
6.4.12 Trace
==============================================================================

The trace field contains execution tracing information for diagnostics
and cross-component correlation.

Examples of trace fields:

- request_id: The unique identifier of the original HermesRequest.
- execution_id: The unique identifier of this Hermes execution.
- pipeline_trace: The execution path through Hermes internal components
  (optional, diagnostic only).

Runtime Usage:
- Runtime stores trace information in the Runtime Context metadata
  section.
- Trace information is for diagnostics only and never affects Runtime
  behaviour.
- The request_id in the trace enables Runtime to correlate the response
  with the original request.

==============================================================================
6.4.13 Runtime Response Processing
==============================================================================

When Runtime receives a HermesResponse, it processes the response
according to the following flow:

Receive HermesResponse
    ↓
Validate Schema
    ↓
Check Status
    ↓
┌─── FAILED ──────────────────────────────────────────────────────┐
│                                                                  │
│  → Runtime Error Handling (Runtime 0.6)                          │
│  → Response Builder constructs Runtime Error Response            │
│                                                                  │
└──────────────────────────────────────────────────────────────────┘
    ↓  (SUCCESS or PARTIAL_SUCCESS)
Store Decision → RuntimeContext.execution_context
    ↓
Store Confidence → RuntimeContext.execution_context
    ↓
Store Execution Plan → RuntimeContext.execution_context
    ↓
Record Warnings → RuntimeContext.warnings
    ↓
Record Metrics → RuntimeContext.metadata
    ↓
Record Trace → RuntimeContext.metadata
    ↓
Continue Runtime Pipeline → Response Builder

Processing steps:

1. Receive HermesResponse: Runtime receives the response from Hermes
   through the Dispatcher (Runtime 0.4).

2. Validate Schema: Runtime verifies that the response conforms to the
   expected schema version and structure.

3. Check Status: Runtime examines the status field.
   - FAILED: Runtime halts the pipeline and triggers error handling.
   - SUCCESS or PARTIAL_SUCCESS: Runtime continues processing.

4. Store Decision: Runtime stores the decision in the Runtime Context
   execution_context section.

5. Store Confidence: Runtime stores the confidence in the Runtime
   Context execution_context section.

6. Store Execution Plan: Runtime stores the execution_plan in the
   Runtime Context execution_context section.

7. Record Warnings: Runtime records any warnings in the Runtime Context
   warnings section.

8. Record Metrics: Runtime records execution metrics in the Runtime
   Context metadata section.

9. Record Trace: Runtime records trace information in the Runtime
   Context metadata section.

10. Continue Runtime Pipeline: Runtime continues the pipeline to the
    Response Builder stage.

==============================================================================
6.4.14 Runtime Parsing Rules
==============================================================================

The following table defines how Runtime maps each HermesResponse field
to its behaviour:

| Response Field | Runtime Behaviour |
|----------------|-------------------|
| version | Verify compatibility with request version |
| status | Determine pipeline continuation (SUCCESS/PARTIAL_SUCCESS → continue, FAILED → halt) |
| decision | Store in RuntimeContext.execution_context |
| confidence | Store in RuntimeContext.execution_context |
| reasoning | Logging and audit only. Never branch execution on reasoning text. |
| execution_plan | Store in RuntimeContext.execution_context for downstream execution |
| warnings | Store in RuntimeContext.warnings |
| metrics | Store in RuntimeContext.metadata for monitoring |
| trace | Store in RuntimeContext.metadata for diagnostics |

Rules:

1. Runtime must never infer semantics beyond the documented contract.
   Each field shall be processed according to its defined behaviour in
   this specification.

2. Runtime must not branch execution based on the content of the
   reasoning field. Reasoning is for explanation purposes only.

3. Runtime must not modify the decision or execution_plan contents
   received from Hermes.

4. Runtime must not interpret the internal structure of the decision
   field beyond storing it in the Runtime Context.

5. Unknown fields in the HermesResponse shall be ignored by Runtime
   unless they are supported by a newer schema version that Runtime
   explicitly supports.

6. Missing optional fields shall not cause processing errors. Runtime
   shall apply documented default behaviour for absent optional fields.

7. Runtime shall treat HermesResponse as an immutable communication
   contract. The response shall not be modified after receipt.

8. Any transformation required by Runtime shall be performed by copying
   data into RuntimeContext rather than modifying HermesResponse. This
   ensures HermesResponse remains an immutable record of Hermes
   execution.
